spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:validate}
    show-sql: false
    properties:
      hibernate:
        format_sql: false

server:
  error:
    include-message: never
    include-stacktrace: never

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:28800000}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:2592000000}

app:
  admin-initial-password: ${ADMIN_INITIAL_PASSWORD}
  tech-initial-password: ${TECH_INITIAL_PASSWORD}
